// Re-export utility types from focused modules for backward compatibility
// This approach maintains existing imports while organizing types into logical modules

// Component-related utilities
export type {
  WithDisplayName,
  ComponentWithDisplayName,
  ForwardRefComponentWithDisplayName,
  HOC,
  Matching,
  Subtract,
  RenderProp,
  ChildrenRenderProp,
  FunctionAsChild,
  ExtractProps,
  ExtractRef,
  PropsOf,
  EventHandler,
  AsyncEventHandler,
  EventHandlerWithContext,
  PreventableEventHandler,
  SetState,
  StateUpdater,
  StateHook,
  ReducerAction,
  ReducerState,
  Reducer,
  AsyncOperationState,
  AsyncOperation,
  PromiseResolver,
  PromiseRejecter,
  DeferredPromise,
  ConditionalProps,
  SwitchProps,
  CaseProps,
  ListProps,
  VirtualizedListProps,
  PerformanceMetrics,
  LazyLoadOptions,
  A11yProps,
  FocusManagement,
  TestProps,
  MockProps,
  DevtoolsProps,
  ComponentInfo,
} from './component-utilities';

// Form-related utilities
export type {
  FormSubmissionState,
  FormField,
  FormFields,
  FormState,
  FormValidator,
  FieldValidator,
  FormValidators,
  SearchResult,
  FilterConfig,
  FileUploadConfig,
  UploadedFile,
} from './form-utilities';

// API-related utilities
export type {
  ApiMethod,
  ApiEndpoint,
  ApiClient,
  ApiHookOptions,
  ApiMutationOptions,
  ChartDataPoint,
  ChartSeries,
  ChartConfig,
} from './api-utilities';

// UI and styling utilities
export type {
  ThemeValue,
  ResponsiveThemeValue,
  ThemeBreakpoints,
  ThemeBreakpoint,
  CSSValue,
  CSSProperty,
  CSSRuleSet,
  ResponsiveCSSValue,
  CSSVariableKey,
  CSSVariables,
  AnimationDirection,
  AnimationFillMode,
  AnimationIterationCount,
  AnimationPlayState,
  AnimationKeyframes,
  AnimationDefinition,
  IconDefinition,
  IconSize,
  IconProps,
  FlexDirection,
  FlexWrap,
  JustifyContent,
  AlignItems,
  AlignContent,
  FlexboxUtilities,
  GridTemplateColumns,
  GridTemplateRows,
  GridAutoFlow,
  GridUtilities,
  SpacingValue,
  SpacingUtilities,
  FontWeight,
  FontSize,
  LineHeight,
  LetterSpacing,
  TextAlign,
  TextTransform,
  TypographyUtilities,
  ColorScale,
  ColorName,
  ColorToken,
  ColorUtilities,
  ShadowSize,
  ShadowUtilities,
  BorderRadius,
  BorderWidth,
  BorderUtilities,
  StyleUtilities,
  MenuItem,
  BreadcrumbItem,
  TabItem,
  NotificationAction,
  Notification,
  ModalAction,
  ConfirmationDialog,
} from './ui-utilities';
